changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - breaking
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Other Changes
      labels:
        - "*"
